import Foundation
import Observation
import SwiftUI

/// App-wide chat read state. The iPhone drawer, the iPad sidebar and folder rows all read
/// from here, so a change from any source shows up everywhere immediately.
///
/// Stores *overrides* on top of what the server lists returned:
///  • `readAt[chatId]` — a local read time (opened here / socket broadcast / mark-unread = 0)
///  • `folderCounts` — the latest `folder_unread_counts` from any response or broadcast
@MainActor @Observable
final class ChatReadState {
    static let shared = ChatReadState()

    private(set) var readAt: [String: TimeInterval] = [:]
    private(set) var folderCounts: [String: Int] = [:]
    /// Chats whose reply is being generated by ANOTHER device (from `chat:active`). The
    /// sidebar shows its spinner for these, like the web client's "generating" state.
    private(set) var generatingElsewhere: Set<String> = []
    /// The chat currently on screen — never shown as unread (web: `id !== $chatId`).
    var openChatId: String?

    @ObservationIgnored private var subscription: SocketSubscription?
    @ObservationIgnored private weak var socket: SocketIOService?

    // MARK: Rules

    /// `isGenerating` = this chat is replying on this device (web: `!active`).
    func isUnread(_ c: Conversation, isGenerating: Bool = false) -> Bool {
        Self.isUnread(updatedAt: c.updatedAt.timeIntervalSince1970,
                      serverReadAt: c.lastReadAt, localReadAt: readAt[c.id],
                      isOpen: c.id == openChatId, isGenerating: isGenerating,
                      isTemporary: c.isTemporary)
    }

    nonisolated static func isUnread(updatedAt: TimeInterval, serverReadAt: TimeInterval?, localReadAt: TimeInterval?,
                                     isOpen: Bool, isGenerating: Bool, isTemporary: Bool) -> Bool {
        if isOpen || isGenerating || isTemporary { return false }
        // A local override replaces the server value — it can be *lower* (mark-unread → 0).
        guard let effective = localReadAt ?? serverReadAt, effective > 0 else { return true }
        // Server timestamps are whole seconds; tolerate drift on a chat read the same second.
        return updatedAt > effective + 0.5
    }

    /// Badge count; shared-with-me folders never show one (web RecursiveFolder).
    func folderUnreadCount(_ folder: ChatFolder) -> Int {
        folder.readonly ? 0 : max(0, folderCounts[folder.id] ?? folder.unreadCount)
    }

    // MARK: Mutations

    func apply(_ r: ReadStateResponse, chatId: String? = nil) {
        if let chatId, let t = r.lastReadAt { readAt[chatId] = t }
        if let counts = r.folderUnreadCounts { folderCounts.merge(counts) { _, new in new } }
    }

    /// Opening a chat: hide the dot now, and tell the server (which tells the web).
    func markOpened(_ chatId: String) {
        guard !chatId.isEmpty, !chatId.hasPrefix("local:") else { return }
        readAt[chatId] = Date().timeIntervalSince1970
        socket?.emit("events:chat", data: ["chat_id": chatId, "data": ["type": "last_read_at"]])
    }

    func markUnread(_ chatId: String, api: APIClient) async throws {
        let r = try await api.markChatUnread(id: chatId)
        readAt[chatId] = r.lastReadAt ?? 0
        apply(r)
    }

    func markAllRead(_ visible: [Conversation], api: APIClient) async throws {
        let r = try await api.markAllChatsRead()
        markLocallyRead(visible)
        // Chats we haven't listed yet: lift every existing override too.
        let now = Date().timeIntervalSince1970
        readAt = readAt.mapValues { max($0, now) }
        apply(r)
    }

    func markFolderRead(_ folderId: String, chats: [Conversation], api: APIClient) async throws {
        let r = try await api.markFolderChatsRead(folderId: folderId)
        markLocallyRead(chats)
        apply(r)
    }

    private func markLocallyRead(_ chats: [Conversation]) {
        let now = Date().timeIntervalSince1970
        for c in chats { readAt[c.id] = max(now, c.updatedAt.timeIntervalSince1970) }
    }

    /// Fresh `GET /folders/` rows carry authoritative `unread_count`s — drop older overrides.
    func adoptServerFolderCounts(_ folders: [ChatFolder]) {
        for f in folders { folderCounts.removeValue(forKey: f.id) }
    }

    /// Fresh server rows: drop overrides the server has caught up with (so they never go stale).
    func reconcile(with conversations: [Conversation]) {
        for c in conversations {
            guard let local = readAt[c.id], let server = c.lastReadAt else { continue }
            if local > 0 ? server >= local : server == 0 { readAt.removeValue(forKey: c.id) }
        }
    }

    // MARK: Chat screen reports (single source of truth)

    /// The chat screen is showing `chatId` (its real server ID — also for chats started
    /// from the new-chat screen, which the sidebar selection never sees).
    func chatScreenOpened(_ chatId: String?) {
        guard let chatId, !chatId.isEmpty, !chatId.hasPrefix("local:") else { return }
        if let previous = openChatId, previous != chatId { markOpened(previous) }
        openChatId = chatId
        markOpened(chatId)
    }

    /// The chat screen left `chatId`. Anything read up to now stays read; a reply that
    /// finishes later correctly shows the dot. Ignored if another chat already took over.
    func chatScreenClosed(_ chatId: String?) {
        guard let chatId, !chatId.isEmpty, !chatId.hasPrefix("local:") else { return }
        markOpened(chatId)
        if openChatId == chatId { openChatId = nil }
    }

    /// A reply finished while its chat is on screen — it was seen, so it is read.
    func chatReplyFinished(_ chatId: String?) {
        guard let chatId, openChatId == chatId else { return }
        markOpened(chatId)
    }

    // MARK: Live updates (another device / the web read a chat)

    /// Marks a chat as generating (or no longer generating) on another device. Chats
    /// this device is replying to itself are shown by `streamingConversationId` instead.
    func setGeneratingElsewhere(_ chatId: String, _ active: Bool) {
        if active {
            guard !generatingElsewhere.contains(chatId) else { return }
            withAnimation(MicroAnimation.quick) { _ = generatingElsewhere.insert(chatId) }
            startVerifyingGenerating()
        } else if generatingElsewhere.contains(chatId) {
            withAnimation(MicroAnimation.quick) { _ = generatingElsewhere.remove(chatId) }
        }
    }
    @ObservationIgnored private weak var activeChatStore: ActiveChatStore?
    @ObservationIgnored private weak var api: APIClient?
    @ObservationIgnored private var verifyTask: Task<Void, Never>?

    /// The `chat:active` false event is sent once. If this device missed it (backgrounded,
    /// socket reconnecting) the spinner would stay forever. While any chat shows as
    /// generating elsewhere, ask the server every few seconds whether it is really still
    /// running, and drop the spinner once it isn't. Network errors never clear a spinner.
    private func startVerifyingGenerating() {
        guard verifyTask == nil else { return }
        verifyTask = Task { @MainActor [weak self] in
            while !Task.isCancelled {
                try? await Task.sleep(nanoseconds: 8_000_000_000)
                guard let self, !Task.isCancelled, !self.generatingElsewhere.isEmpty else { break }
                await self.verifyGeneratingNow()
            }
            self?.verifyTask = nil
        }
    }

    /// One pass: clears the spinner of every chat the server says has nothing running.
    /// Also called on socket connect/reconnect and when returning to the app.
    func verifyGeneratingNow() async {
        guard let api else { return }
        for chatId in generatingElsewhere {
            guard let running = try? await api.getTasksForChat(chatId: chatId) else { continue }
            if running.isEmpty {
                setGeneratingElsewhere(chatId, false)
                activeChatStore?.reconcileStreaming(chatId: chatId)
            }
        }
    }

    func attach(to socket: SocketIOService?, store: ActiveChatStore? = nil, api: APIClient? = nil) {
        subscription?.dispose()
        subscription = nil
        verifyTask?.cancel()
        verifyTask = nil
        self.socket = socket
        self.activeChatStore = store
        self.api = api
        readAt = [:]; folderCounts = [:]; openChatId = nil; generatingElsewhere = []
        guard let socket else { return }
        subscription = socket.addChatEventHandler { [weak self] event, _ in
            // Cheap filter off the main thread — this handler sees every streaming token.
            guard let data = event["data"] as? [String: Any], let type = data["type"] as? String else { return }
            let chatId = event["chat_id"] as? String
            // Track chats that are generating on another device, for the sidebar spinner.
            if type == "chat:active", let chatId,
               let active = (data["data"] as? [String: Any])?["active"] as? Bool {
                Task { @MainActor [weak self] in self?.setGeneratingElsewhere(chatId, active) }
            }
            // Web Chat.svelte: when the open chat's reply finishes, mark it read so the
            // reply doesn't leave it "unread" on other devices.
            if type == "chat:active", (data["data"] as? [String: Any])?["active"] as? Bool == false, let chatId {
                Task { @MainActor [weak self] in
                    if self?.openChatId == chatId { self?.markOpened(chatId) }
                    // Safety net: the server says it's done — never leave a spinner behind.
                    self?.activeChatStore?.reconcileStreaming(chatId: chatId)
                }
                return
            }
            guard type == "chat:list", let inner = data["data"] as? [String: Any],
                  inner["last_read_at"] != nil || inner["folder_unread_counts"] != nil else { return }
            let r = ReadStateResponse(json: inner)
            Task { @MainActor [weak self] in self?.apply(r, chatId: chatId) }
        }
    }
}
